name: Format Markdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Format
        run: |
          npm install
          ./node_modules/.bin/prettier README.md docs/**/*.md --write
      - name: Commit & Push Markdown format changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add .
          git commit -m "style: format markdown files" || true
          git push
